#+TITLE:    text.source-location README
#+AUTHOR:   Jan Moringen
#+EMAIL:    jmoringe@techfak.uni-bielefeld.de
#+LANGUAGE: en

* STARTED Introduction

  Consider the following error report produced using the
  ~text.source-location~ system.

  It demonstrates the following functionalities

  + Multiple source locations can be annotated

  + Source locations from multiple sources (in this case files) can be
    referenced

  + For multiple source locations in a single source which are
    sufficiently far apart, the irrelevant parts are skipped and
    replaced with ellipsis

  + Horizontal ellipsis

  + Line numbers

  + Annotation for a source location spanning multiple lines


  #+BEGIN_EXAMPLE
    Multiple definitions of variable CONFIGURE.ENABLE-ARGS.

      In /home/jmoringe/code/citec/citk/recipes/templates/ci/autotools.template:
        3 │
        4 │     "inherit": [
        5 │         "autotools-base",
          │         ▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔included here
        6 │         "warnings"
        7 │     ],

      In /home/jmoringe/code/citec/citk/recipes/templates/ci/autotools-base.template:
        23 │         "configure.enable":          "${configure.enable:${mode}|${configure.enable:default}}",
        24 │         "configure.enable:default":  [],
        25 │         "configure.enable-args":     "  --enable-${configure.enable} \\\n",
           │         ▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔first definition
        26 │
        27 │         "configure.disable":         "${configure.disable:${mode}|${configure.disable:default}}",

         ⁞ ⁞  ⁞

        31 │         "configure.args":            "@{confi…
        32 │
           │         ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
        33 │         "configure.enable-args":     [
        34 │             "  --enable-${configure.enable} \…
        35 │         ],
           │ ▔▔▔▔▔▔▔▔▔second definition
        36 │
        37 │         "shell.command":             "${shell…
  #+END_EXAMPLE

* STARTED Concepts

  + sequence of characters :: E.g. a string (ignoring Unicode issues)

  + source :: A description (e.g. filename, buffer name) and,
              optionally, associated content.

  + index :: Given a *sequence of characters*, before the first
             character, between two adjacent characters or after the
             last character. The index before the first character
             is 0.

  + position :: Abstract version of *index*.

                May be encoded as an *index* or as a *line* and a
                *column*.

  + range :: A pair of *positions* bounding a contiguous sub-sequence
             of a sequence.

  + location :: A *source* and a *range*

  + annotation :: A *location* and an annotation text.

  + line ::

    + Internal representation :: [0, ∞)
    + User-facing represetation :: [1, ∞)

  + column :: A horizontal offset in characters from the beginning of
              the line.

    + Internal representation :: [0, ∞)
    + User-facing represetatnion :: [0, ∞)

* TODO Tutorial

* TODO Dictionary

* settings                                                         :noexport:
#+OPTIONS: num:nil
#+SEQ_TODO: TODO STARTED | DONE
